/*
## API APPSCRIPTS

-----------------------------

### GET & FILTER

This endpoint allows you to get and filter data from a Google spreadsheet using the provided spreadsheet ID. The request is made using the GET method, and an empty JSON body with the "NAME_SHEET" field is passed
*/
POST /googlesheet/get/{{SPREADSHEET_ID_GOOGLE}}
Content-Type: application/json

{
  "PRODUCTOS": {}
}

HTTP/1.1 404  - Not Found
content-length: 272
content-type: text/html; charset=UTF-8
date: Mon, 17 Jun 2024 22:05:44 GMT
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
connection: close